<a href="https://colab.research.google.com/github/CHHAVI0110/linear-regression-housing-forecast/blob/main/House_Price_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PREDICTIVE_HOUSING_ANALYSIS

In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

PROCESS_1 : LOAD THE DATASET




In [4]:
from sklearn.datasets  import fetch_california_housing

In [5]:
df=fetch_california_housing()

In [6]:
df

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [7]:
dataset = pd.DataFrame(df.data)

In [8]:
dataset

0     1         2         3       4         5      6       7
0      8.3252  41.0  6.984127  1.023810   322.0  2.555556  37.88 -122.23
1      8.3014  21.0  6.238137  0.971880  2401.0  2.109842  37.86 -122.22
2      7.2574  52.0  8.288136  1.073446   496.0  2.802260  37.85 -122.24
3      5.6431  52.0  5.817352  1.073059   558.0  2.547945  37.85 -122.25
4      3.8462  52.0  6.281853  1.081081   565.0  2.181467  37.85 -122.25
...       ...   ...       ...       ...     ...       ...    ...     ...
20635  1.5603  25.0  5.045455  1.133333   845.0  2.560606  39.48 -121.09
20636  2.5568  18.0  6.114035  1.315789   356.0  3.122807  39.49 -121.21
20637  1.7000  17.0  5.205543  1.120092  1007.0  2.325635  39.43 -121.22
20638  1.8672  18.0  5.329513  1.171920   741.0  2.123209  39.43 -121.32
20639  2.3886  16.0  5.254717  1.162264  1387.0  2.616981  39.37 -121.24

[20640 rows x 8 columns]

In [9]:
dataset.columns=df.feature_names

In [10]:
dataset.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

PROCESS_2 : EXTRACT INPUT AND OUTPUT

In [11]:
x=dataset

In [12]:
x

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [13]:
y=df.target
y

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

PROCESS_3 : TRAIN A LINEAR REGRESSION MODEL

In [14]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [17]:
x_train

MedInc  HouseAge   AveRooms  AveBedrms  Population  AveOccup  Latitude  \
2582   1.1742      25.0   3.488127   1.021108       794.0  2.094987     40.86   
8177   4.4831      36.0   5.256098   0.981707       838.0  2.554878     33.80   
8190   5.3441      36.0   5.633484   0.954751       508.0  2.298643     33.79   
10015  4.3523       5.0   6.425532   1.021277       376.0  2.666667     39.25   
6037   1.4063      51.0   4.446429   1.026786       368.0  3.285714     34.06   
...       ...       ...        ...        ...         ...       ...       ...   
2717   1.1853      16.0   3.996942   1.097859       961.0  2.938838     32.80   
19202  1.5026      38.0   3.192817   0.994329      1071.0  2.024575     38.43   
5394   2.6402      43.0   3.707317   1.036585       705.0  2.865854     34.03   
12359  2.5489      18.0  11.901869   2.163551       411.0  1.920561     33.78   
14512  6.0891       5.0   5.469595   0.918919      1063.0  3.591216     32.91   

       Longitude  
2582     -124.09  
8177     -118.09  
8190     -118.13  
10015    -121.20  
6037     -117.73  
...          ...  
2717     -115.57  
19202    -122.71  
5394     -118.38  
12359    -116.53  
14512    -117.16  

[16512 rows x 8 columns]

In [18]:
x_test

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
639    3.3750      47.0  4.473684   0.943609       540.0  2.030075     37.72   
17943  3.1702      25.0  4.316570   1.088211      2529.0  2.084913     37.34   
5498   2.9338      18.0  2.866228   0.967105       884.0  1.938596     34.00   
18070  7.5000      31.0  7.611650   1.046117      1190.0  2.888350     37.29   
3015   3.0882      14.0  7.001727   1.359240      1581.0  2.730570     34.95   
...       ...       ...       ...        ...         ...       ...       ...   
20360  6.3303      16.0  8.287611   1.123894      1556.0  3.442478     34.17   
16387  2.9821      32.0  6.576923   1.115385       138.0  2.653846     38.02   
3964   3.5000      21.0  4.304913   1.075145      1824.0  2.635838     34.20   
8571   7.8924      37.0  6.554667   1.066667       920.0  2.453333     33.90   
17263  2.5506      23.0  3.628070   1.154386      1898.0  3.329825     34.42   

       Longitude  
639      -122.15  
17943    -121.95  
5498     -118.41  
18070    -122.01  
3015     -119.16  
...          ...  
20360    -118.94  
16387    -121.27  
3964     -118.58  
8571     -118.40  
17263    -119.71  

[4128 rows x 8 columns]

PROCESS_4 : SCALE THE VALUE

---



In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
x_train=scaler.fit_transform(x_train)
x_train

array([[-0.4347103 ,  0.90676506, -0.49399751, ...,  0.01867563,
         0.98075258, -1.41729165],
       [-0.37979575, -1.79355936, -0.25337307, ...,  0.04327938,
        -0.80380634,  0.7007846 ],
       [-0.48311763, -0.91992499, -0.34056881, ..., -0.0316938 ,
        -0.72397081,  1.09542616],
       ...,
       [-1.03580766, -1.0787676 ,  0.24333189, ..., -0.02800432,
         2.42718455, -1.95680164],
       [ 4.091137  , -0.84050368,  1.30644422, ..., -0.02923667,
         1.04180328, -1.31238693],
       [-0.10051455, -0.12571192,  0.23314072, ..., -0.03560682,
         1.41749989, -0.90275898]])

In [ ]:
x_test=scaler.transform(x_test)
x_test

array([[ 0.10142072, -0.60223976, -0.36823905, ...,  0.17573404,
        -0.31070454, -0.4431764 ],
       [ 2.3419659 ,  0.66850114,  0.53538586, ..., -0.07609786,
        -0.70048977,  0.5659071 ],
       [-0.38688491, -0.44339715, -0.737945  , ..., -0.10997017,
        -0.69109736,  0.59587988],
       ...,
       [-1.0452246 ,  0.74792245, -0.76599553, ...,  0.10166554,
        -0.77093289,  0.68080275],
       [-0.23907062,  0.58907984, -0.08307239, ..., -0.09695953,
         0.47356215, -1.17750944],
       [ 0.51592502,  0.58907984,  0.09834956, ..., -0.02625499,
        -0.8366798 ,  0.72576191]])

PROCESS_5 : MODEL TRAINING USING THE LINEAR REGRESSION

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [26]:
from sklearn.metrics import mean_squared_error, r2_score

In [20]:
model = RandomForestRegressor(n_estimators=100, random_state=42)

In [22]:
model.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

PROCESS_6 : PREDICTION

In [24]:
y_pred = model.predict(x_test)


PROCESS_7 : ACCURACY CHECK

In [27]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [28]:
print(f"Mean Squared Error: {mse:.3f}")
print(f"R² Score: {r2:.3f}")

Mean Squared Error: 0.259
R² Score: 0.799


**R-squared score indicates model accuracy.**